import mongoose from 'mongoose';
import User from '../models/User.js';
import dotenv from 'dotenv';
dotenv.config();

await mongoose.connect(process.env.MONGODB_URI.trim(), {
  serverSelectionTimeoutMS: 15000,
  tlsInsecure: true,
});
console.log('✅ MongoDB connected\n');

const users = [
  // ─── EGYPT ───────────────────────────────────────────────────────────────
  { name:'Ahmed Hassan', email:'ahmed.hassan@swaply.eg', password:'password123', avatar:'https://randomuser.me/api/portraits/men/11.jpg', bio:'Full-Stack developer & UI/UX enthusiast from Cairo. 7 years building products for the MENA market. Love teaching web dev and design thinking.', country:'Egypt', timeZone:'Africa/Cairo', languages:['Arabic','English'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:180, tokensEarned:340, totalSessionsTaught:42, averageRating:4.8, totalRatings:38, level:5, experience:2100, skillsToTeach:[{name:'UI/UX Design',category:'Design',level:'expert',tokensPerHour:30},{name:'React Development',category:'Programming',level:'advanced',tokensPerHour:25}], skillsToLearn:[{name:'Machine Learning',category:'AI',level:'beginner',tokensPerHour:20}] },
  { name:'Nour El-Sayed', email:'nour.elsayed@swaply.eg', password:'password123', avatar:'https://randomuser.me/api/portraits/women/44.jpg', bio:'Graphic designer & visual storyteller from Alexandria. Passionate about branding, typography, and teaching Arabic calligraphy online.', country:'Egypt', timeZone:'Africa/Cairo', languages:['Arabic','English','French'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:120, tokensEarned:210, totalSessionsTaught:27, averageRating:4.9, totalRatings:24, level:4, experience:1600, skillsToTeach:[{name:'Graphic Design',category:'Design',level:'expert',tokensPerHour:25},{name:'Arabic Calligraphy',category:'Arts',level:'advanced',tokensPerHour:20},{name:'French Language',category:'Language',level:'advanced',tokensPerHour:18}], skillsToLearn:[{name:'Digital Marketing',category:'Business',level:'beginner',tokensPerHour:15}] },
  { name:'Youssef Khalil', email:'youssef.khalil@swaply.eg', password:'password123', avatar:'https://randomuser.me/api/portraits/men/32.jpg', bio:'Data scientist at a Cairo fintech startup. Loves teaching Python, data analysis, and machine learning to Arab youth.', country:'Egypt', timeZone:'Africa/Cairo', languages:['Arabic','English'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:95, tokensEarned:180, totalSessionsTaught:19, averageRating:4.7, totalRatings:17, level:3, experience:950, skillsToTeach:[{name:'Python Programming',category:'Programming',level:'advanced',tokensPerHour:28},{name:'Data Science',category:'AI',level:'advanced',tokensPerHour:32},{name:'Machine Learning',category:'AI',level:'intermediate',tokensPerHour:30}], skillsToLearn:[{name:'Public Speaking',category:'Soft Skills',level:'beginner',tokensPerHour:10}] },
  // ─── USA ─────────────────────────────────────────────────────────────────
  { name:'Marcus Johnson', email:'marcus.johnson@swaply.us', password:'password123', avatar:'https://randomuser.me/api/portraits/men/52.jpg', bio:'Senior product designer at a San Francisco tech company. 10 years of UX strategy, user research, and design systems. Available for 1-on-1 mentoring.', country:'United States', timeZone:'America/Los_Angeles', languages:['English','Spanish'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:250, tokensEarned:520, totalSessionsTaught:68, averageRating:4.9, totalRatings:61, level:7, experience:3400, skillsToTeach:[{name:'UI/UX Design',category:'Design',level:'expert',tokensPerHour:40},{name:'Product Strategy',category:'Business',level:'expert',tokensPerHour:45},{name:'Figma',category:'Design',level:'expert',tokensPerHour:35}], skillsToLearn:[{name:'Arabic Language',category:'Language',level:'beginner',tokensPerHour:15}] },
  { name:'Sarah Mitchell', email:'sarah.mitchell@swaply.us', password:'password123', avatar:'https://randomuser.me/api/portraits/women/68.jpg', bio:'Full-stack engineer & coding bootcamp instructor from Austin, TX. Helping beginners land their first dev job through hands-on mentoring.', country:'United States', timeZone:'America/Chicago', languages:['English'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:310, tokensEarned:640, totalSessionsTaught:81, averageRating:4.8, totalRatings:75, level:8, experience:4100, skillsToTeach:[{name:'JavaScript',category:'Programming',level:'expert',tokensPerHour:35},{name:'Node.js',category:'Programming',level:'advanced',tokensPerHour:32},{name:'Web Development',category:'Programming',level:'expert',tokensPerHour:38}], skillsToLearn:[{name:'Photography',category:'Arts',level:'beginner',tokensPerHour:10}] },
  { name:'David Chen', email:'david.chen@swaply.us', password:'password123', avatar:'https://randomuser.me/api/portraits/men/76.jpg', bio:'Digital marketing consultant from New York. Specialized in growth hacking, SEO, and social media strategy for startups.', country:'United States', timeZone:'America/New_York', languages:['English','Mandarin'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:140, tokensEarned:295, totalSessionsTaught:34, averageRating:4.6, totalRatings:30, level:5, experience:1750, skillsToTeach:[{name:'Digital Marketing',category:'Business',level:'expert',tokensPerHour:38},{name:'SEO',category:'Business',level:'advanced',tokensPerHour:30},{name:'Content Strategy',category:'Business',level:'advanced',tokensPerHour:28}], skillsToLearn:[{name:'UI/UX Design',category:'Design',level:'beginner',tokensPerHour:20}] },
  // ─── LONDON ──────────────────────────────────────────────────────────────
  { name:'James Harrison', email:'james.harrison@swaply.uk', password:'password123', avatar:'https://randomuser.me/api/portraits/men/22.jpg', bio:'Cambridge-educated English language tutor & business communication coach. 12 years helping professionals master English for global careers.', country:'United Kingdom', timeZone:'Europe/London', languages:['English','French','German'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:200, tokensEarned:480, totalSessionsTaught:93, averageRating:4.9, totalRatings:87, level:9, experience:4700, skillsToTeach:[{name:'English Language',category:'Language',level:'expert',tokensPerHour:30},{name:'Business Communication',category:'Soft Skills',level:'expert',tokensPerHour:35},{name:'IELTS Preparation',category:'Language',level:'expert',tokensPerHour:32}], skillsToLearn:[{name:'Arabic Language',category:'Language',level:'beginner',tokensPerHour:15}] },
  { name:'Emma Clarke', email:'emma.clarke@swaply.uk', password:'password123', avatar:'https://randomuser.me/api/portraits/women/29.jpg', bio:'UX researcher & service designer from London. Working with NHS and fintech clients. Passionate about accessible, inclusive design.', country:'United Kingdom', timeZone:'Europe/London', languages:['English','Spanish'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:175, tokensEarned:360, totalSessionsTaught:46, averageRating:4.8, totalRatings:42, level:6, experience:2300, skillsToTeach:[{name:'UX Research',category:'Design',level:'expert',tokensPerHour:38},{name:'UI/UX Design',category:'Design',level:'advanced',tokensPerHour:35},{name:'Accessibility Design',category:'Design',level:'advanced',tokensPerHour:32}], skillsToLearn:[{name:'Data Science',category:'AI',level:'beginner',tokensPerHour:20}] },
  { name:'Oliver Thompson', email:'oliver.thompson@swaply.uk', password:'password123', avatar:'https://randomuser.me/api/portraits/men/41.jpg', bio:'Fintech product manager and startup advisor in London. Teaching product management, agile, and how to build MVPs from 0 to launch.', country:'United Kingdom', timeZone:'Europe/London', languages:['English','French'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:130, tokensEarned:270, totalSessionsTaught:31, averageRating:4.7, totalRatings:28, level:5, experience:1550, skillsToTeach:[{name:'Product Management',category:'Business',level:'expert',tokensPerHour:42},{name:'Agile & Scrum',category:'Business',level:'advanced',tokensPerHour:35},{name:'Startup Strategy',category:'Business',level:'expert',tokensPerHour:45}], skillsToLearn:[{name:'Machine Learning',category:'AI',level:'beginner',tokensPerHour:20}] },
  // ─── KSA ─────────────────────────────────────────────────────────────────
  { name:'Khalid Al-Rashidi', email:'khalid.alrashidi@swaply.sa', password:'password123', avatar:'https://randomuser.me/api/portraits/men/55.jpg', bio:'Software architect & cloud engineer from Riyadh with 9 years at Saudi Aramco. Teaching AWS, system design, and backend engineering.', country:'Saudi Arabia', timeZone:'Asia/Riyadh', languages:['Arabic','English'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:220, tokensEarned:430, totalSessionsTaught:55, averageRating:4.8, totalRatings:50, level:7, experience:2750, skillsToTeach:[{name:'Cloud Architecture',category:'DevOps',level:'expert',tokensPerHour:45},{name:'System Design',category:'Programming',level:'expert',tokensPerHour:40},{name:'AWS',category:'DevOps',level:'expert',tokensPerHour:38}], skillsToLearn:[{name:'UI/UX Design',category:'Design',level:'beginner',tokensPerHour:20}] },
  { name:'Fatima Al-Zahrani', email:'fatima.alzahrani@swaply.sa', password:'password123', avatar:'https://randomuser.me/api/portraits/women/55.jpg', bio:'Certified business analyst and project manager from Jeddah. Helping teams adopt digital transformation with PMP and CBAP certifications.', country:'Saudi Arabia', timeZone:'Asia/Riyadh', languages:['Arabic','English'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:160, tokensEarned:310, totalSessionsTaught:38, averageRating:4.7, totalRatings:34, level:5, experience:1900, skillsToTeach:[{name:'Business Analysis',category:'Business',level:'expert',tokensPerHour:35},{name:'Project Management',category:'Business',level:'expert',tokensPerHour:38},{name:'Arabic Language',category:'Language',level:'expert',tokensPerHour:20}], skillsToLearn:[{name:'Data Science',category:'AI',level:'beginner',tokensPerHour:20}] },
  { name:'Abdullah Al-Ghamdi', email:'abdullah.alghamdi@swaply.sa', password:'password123', avatar:'https://randomuser.me/api/portraits/men/60.jpg', bio:'Entrepreneur and e-commerce specialist from Dammam. Built 3 successful online businesses and love teaching others how to start theirs.', country:'Saudi Arabia', timeZone:'Asia/Riyadh', languages:['Arabic','English'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:100, tokensEarned:195, totalSessionsTaught:22, averageRating:4.6, totalRatings:20, level:4, experience:1100, skillsToTeach:[{name:'E-Commerce',category:'Business',level:'expert',tokensPerHour:30},{name:'Entrepreneurship',category:'Business',level:'expert',tokensPerHour:35},{name:'Digital Marketing',category:'Business',level:'advanced',tokensPerHour:28}], skillsToLearn:[{name:'Python Programming',category:'Programming',level:'beginner',tokensPerHour:15}] },
  // ─── UAE ─────────────────────────────────────────────────────────────────
  { name:'Omar Al-Mansoori', email:'omar.almansoori@swaply.ae', password:'password123', avatar:'https://randomuser.me/api/portraits/men/71.jpg', bio:'AI engineer and innovation lead at a Dubai tech hub. Bridging the gap between cutting-edge AI research and real business applications.', country:'United Arab Emirates', timeZone:'Asia/Dubai', languages:['Arabic','English','Hindi'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:280, tokensEarned:570, totalSessionsTaught:72, averageRating:4.9, totalRatings:65, level:8, experience:3600, skillsToTeach:[{name:'Machine Learning',category:'AI',level:'expert',tokensPerHour:50},{name:'Deep Learning',category:'AI',level:'expert',tokensPerHour:55},{name:'Python Programming',category:'Programming',level:'expert',tokensPerHour:40}], skillsToLearn:[{name:'Business Communication',category:'Soft Skills',level:'intermediate',tokensPerHour:15}] },
  { name:'Layla Al-Farsi', email:'layla.alfarsi@swaply.ae', password:'password123', avatar:'https://randomuser.me/api/portraits/women/71.jpg', bio:'Interior designer & creative director from Abu Dhabi. Blending Islamic heritage with modern aesthetics. Teaching design fundamentals and creative thinking.', country:'United Arab Emirates', timeZone:'Asia/Dubai', languages:['Arabic','English','French'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:190, tokensEarned:380, totalSessionsTaught:48, averageRating:4.8, totalRatings:43, level:6, experience:2400, skillsToTeach:[{name:'Interior Design',category:'Design',level:'expert',tokensPerHour:40},{name:'Graphic Design',category:'Design',level:'advanced',tokensPerHour:30},{name:'Creative Thinking',category:'Soft Skills',level:'advanced',tokensPerHour:25}], skillsToLearn:[{name:'Digital Marketing',category:'Business',level:'intermediate',tokensPerHour:18}] },
  { name:'Rania Mahmoud', email:'rania.mahmoud@swaply.ae', password:'password123', avatar:'https://randomuser.me/api/portraits/women/82.jpg', bio:'HR consultant and career coach in Dubai. Former KPMG consultant helping professionals build standout CVs, ace interviews, and navigate career pivots.', country:'United Arab Emirates', timeZone:'Asia/Dubai', languages:['Arabic','English'], isTeacher:true, isVerified:true, isActive:true, role:'teacher', tokens:145, tokensEarned:290, totalSessionsTaught:35, averageRating:4.7, totalRatings:32, level:5, experience:1750, skillsToTeach:[{name:'Career Coaching',category:'Soft Skills',level:'expert',tokensPerHour:35},{name:'Interview Prep',category:'Soft Skills',level:'expert',tokensPerHour:30},{name:'CV Writing',category:'Soft Skills',level:'expert',tokensPerHour:25}], skillsToLearn:[{name:'Data Science',category:'AI',level:'beginner',tokensPerHour:20}] },
];

let created = 0, skipped = 0;
console.log(`📋 Inserting ${users.length} users...\n`);

for (const u of users) {
  const exists = await User.findOne({ email: u.email.toLowerCase() });
  if (exists) { console.log(`⏭️  Skipped: ${u.name}`); skipped++; continue; }
  const user = new User(u);
  await user.save();
  console.log(`✅ ${u.name.padEnd(24)} | ${u.country.padEnd(22)} | ${u.languages.join(', ')}`);
  created++;
}

console.log(`\n${'='.repeat(62)}`);
console.log(`🎉 Done!  Created: ${created}   Skipped: ${skipped}`);
console.log(`${'='.repeat(62)}`);
console.log('\n🇪🇬 Egypt  — Ahmed Hassan, Nour El-Sayed, Youssef Khalil');
console.log('🇺🇸 USA    — Marcus Johnson, Sarah Mitchell, David Chen');
console.log('🇬🇧 London — James Harrison, Emma Clarke, Oliver Thompson');
console.log('🇸🇦 KSA    — Khalid Al-Rashidi, Fatima Al-Zahrani, Abdullah Al-Ghamdi');
console.log('🇦🇪 UAE    — Omar Al-Mansoori, Layla Al-Farsi, Rania Mahmoud');
console.log('\n🔑 Password for all: password123\n');

process.exit(0);
